### ISSUE TITLE
RIPE JSON malformed conducting traixroute to crash 

### ISSUE THREAD

**Issue by mbruyere** [gnomikos/traIXroute#5] opened 2017-06-20 06:59 UTC
With the lasted version 2.1.1 installed with pip3. 

Find attached a ripejson file with a single traceroute who can make it crash traixroute 
some RIPE JSON ATLAS trace may be malformed and cause TraIXroute to crash. 
[5009crashingTraixroute.json.txt](https://github.com/gnomikos/traIXroute/files/1087250/5009crashingTraixroute.json.txt)

sudo traixroute import -ripejson 5009crashingTraixroute.json

Please add exception in your code to have traIXroute in case of malformed trace to continue until this end of the JSON.  

Traceback (most recent call last):
  File "/usr/local/bin/traixroute", line 11, in <module>
    sys.exit(run_traixroute())
  File "/usr/local/lib/python3.6/site-packages/traixroute/application.py", line 365, in run_traixroute
    traIXroute_module.main()
  File "/usr/local/lib/python3.6/site-packages/traixroute/application.py", line 317, in main
    for rule_hits, json_obj in executor.map(analyze_measurement, input_list):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/traixroute/application.py", line 282, in analyze_measurement
    info] = json_handle.export_trace_from_ripe_file(entry)
  File "/usr/local/lib/python3.6/site-packages/traixroute/handler/handle_json.py", line 185, in export_trace_from_ripe_file
    current_info.append(str(hop['result'][0]['rtt']) + ' ms')
KeyError: 'rtt'

**Comment by slowr** [comment] 2017-06-27 18:06
The problem is resolved in the v2.2-beta branch. We will update the pypy version somewhere inside these days. Thanks alot for reporting the issue!

Best,
Dimitris

**Closed as completed by slowr** 2017-06-27 18:06 UTC
Labels: bug
